/**
 * Five elements: Wood, Fire, Earth, Metal, Water.
 * Used for personality and compatibility logic.
 */
export const ELEMENTS = {
  WOOD: 'Wood',
  FIRE: 'Fire',
  EARTH: 'Earth',
  METAL: 'Metal',
  WATER: 'Water',
};

export const ELEMENT_ORDER = [ELEMENTS.WOOD, ELEMENTS.FIRE, ELEMENTS.EARTH, ELEMENTS.METAL, ELEMENTS.WATER];

// Generating cycle: Wood → Fire → Earth → Metal → Water → Wood
export const GENERATING = {
  [ELEMENTS.WOOD]: ELEMENTS.FIRE,
  [ELEMENTS.FIRE]: ELEMENTS.EARTH,
  [ELEMENTS.EARTH]: ELEMENTS.METAL,
  [ELEMENTS.METAL]: ELEMENTS.WATER,
  [ELEMENTS.WATER]: ELEMENTS.WOOD,
};

// Who generates whom (reverse lookup for "is generated by")
export const GENERATED_BY = {
  [ELEMENTS.FIRE]: ELEMENTS.WOOD,
  [ELEMENTS.EARTH]: ELEMENTS.FIRE,
  [ELEMENTS.METAL]: ELEMENTS.EARTH,
  [ELEMENTS.WATER]: ELEMENTS.METAL,
  [ELEMENTS.WOOD]: ELEMENTS.WATER,
};

// Controlling cycle: Wood→Earth, Earth→Water, Water→Fire, Fire→Metal, Metal→Wood
export const CONTROLS = {
  [ELEMENTS.WOOD]: ELEMENTS.EARTH,
  [ELEMENTS.EARTH]: ELEMENTS.WATER,
  [ELEMENTS.WATER]: ELEMENTS.FIRE,
  [ELEMENTS.FIRE]: ELEMENTS.METAL,
  [ELEMENTS.METAL]: ELEMENTS.WOOD,
};

export const CONTROLLED_BY = {
  [ELEMENTS.EARTH]: ELEMENTS.WOOD,
  [ELEMENTS.WATER]: ELEMENTS.EARTH,
  [ELEMENTS.FIRE]: ELEMENTS.WATER,
  [ELEMENTS.METAL]: ELEMENTS.FIRE,
  [ELEMENTS.WOOD]: ELEMENTS.METAL,
};

export const ELEMENT_SYMBOLS = {
  [ELEMENTS.WOOD]: '🌳',
  [ELEMENTS.FIRE]: '🔥',
  [ELEMENTS.EARTH]: '🏔️',
  [ELEMENTS.METAL]: '⚙️',
  [ELEMENTS.WATER]: '💧',
};

export const ELEMENT_COLORS = {
  [ELEMENTS.WOOD]: '#5a8f7b',
  [ELEMENTS.FIRE]: '#c97a5a',
  [ELEMENTS.EARTH]: '#a88b4a',
  [ELEMENTS.METAL]: '#8a9bb0',
  [ELEMENTS.WATER]: '#5a7a9f',
};
